// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function BlocgList(Props) {
  return React.createElement("h1", undefined, "Blog list");
}

var make = BlocgList;

export {
  make ,
  
}
/* react Not a pure module */
