// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("h1", undefined, React.createElement("span", undefined, "hello!"));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
