// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "../node_modules/reason-react/src/ReasonReactRouter.js";
import * as Nav$ReactHooksTemplate from "./components/Nav.js";
import * as BlocgList$ReactHooksTemplate from "./components/BlocgList.js";

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var tmp;
  var exit = 0;
  if (match && match[0] === "blog" && !match[1]) {
    tmp = React.createElement(BlocgList$ReactHooksTemplate.make, { });
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = React.createElement("div", undefined, "404");
  }
  return React.createElement(React.Fragment, undefined, React.createElement(Nav$ReactHooksTemplate.make, { }), tmp);
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
