// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Nav(Props) {
  return React.createElement("nav", undefined, "hello");
}

var make = Nav;

export {
  make ,
  
}
/* react Not a pure module */
